### PR TITLE
v2.1.0

### PR DESCRIPTION
**Pull request by nekuz0r**
# Do not merge !

## v2.1.0
  * **Update:** libWiringPi to [custom][nekuz0r-libWiringPi] v2.25 `nekuz0r`
  * **Update:** wiringPiISR now keeps event loop running `nekuz0r`
  * **Update:** piModelNames string array `nekuz0r`
  * **Update:** piMakerNames string array `nekuz0r`
  * **Update:** install.sh now clone tagged version of the custom libWiringPi
  * **Add:** support for node 0.12.0
  * **Add:** raspberry pi A+ support `nekuz0r`
  * **Add:** raspberry pi 2 support `nekuz0r`
  * **Add:** constant PI_MODEL_AP `nekuz0r`
  * **Add:** constant PI_MODEL_2 `nekuz0r`
  * **Add:** constant PI_MARKER_MBEST `nekuz0r`
  * **Add:** wiringPiISRCancel `nekuz0r`
  * **Add:** wiringPiSPISetupMode `nekuz0r`
  * **Fix:** blink.js example `louterrailloune`
  * **Fix:** SPI speed select argument `noddy76`

### CODE REVIEW

**Comment by nekuz0r** [comment]
Please review and test ;)

**Comment by nekuz0r** [comment]
**install:** `npm install git+https://git@github.com/nekuz0r/wiring-pi.git#incoming-node-v0.12.x`

**Comment by dirkels** [comment]
When is milestone v2.1.0 due? spend quit some time finding out v2.0.0 need a lower node and newer wiringPi version to work on my Raspberry Pi 2. Saw that v2.1.0 should fix this.

**Comment by nekuz0r** [comment]
By the end of this week, finishing some testing.

**Comment by dirkels** [comment]
Thanks, it's great but got a bit turned off by the fact that wiring-pi uses a port of the actual wiringPI library and not link against the actual library...

**Comment by nekuz0r** [comment]
That's because some additions/improvements have been done to libWiringPi, and Drogon never answer me to my mail.
But all the upstream patches are merged in.

**Comment by dirkels** [comment]
And it does make it a complete package that does not need to rely on other packages been installed. With that information in mind I guess I will have to overcome my aversion against code duplication this time :)

**Comment by schnubb** [comment]
Hey,
so... are there still any plans to release the 2.1.0 version?
or are you still testing?

**Comment by nekuz0r** [comment]
Published on NPM

**Comment by schnubb** [comment]
wow, that was quick :+1: 
thx!

**Pull request merged**
