### PR TITLE
Added scope for dispatchInterrupt and solved #30

### PR DESCRIPTION
**Pull request by taoyuan**
The solution is here: https://github.com/nwjs/nw.js/issues/3289.

### CODE REVIEW

**Comment by Illizian** [comment]
Whilst I cannot analyse the implications of `HandleScope scope(isolate);` I have built & used this fork and it undoubtedly resolves #30.

@taoyuan Perhaps an increment of the the version to `0.2.1` and an entry to the `CHANGELOG.md` should also be made?

**Comment by taoyuan** [comment]
@Illizian It's done. :)

**Comment by nekuz0r** [comment]
LGTM :+1:

**Comment by nekuz0r** [comment]
Merging, will release it tonight as 2.1.1

**Comment by nekuz0r** [comment]
Published on NPM

**Pull request merged**
